services:
  - type: web
    name: codesentinel-backend
    runtime: python
    plan: free

    rootDir: codesentinel-ai/backend

    buildCommand: pip install -r requirements.txt

    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT

    autoDeploy: true

    healthCheckPath: /health

    envVars:
      - key: APP_ENV
        value: production

      - key: DATABASE_URL
        value: sqlite:///./codesentinel.db

      - key: GROQ_MODEL
        value: openai/gpt-oss-120b

      - key: ALLOWED_ORIGINS
        value: https://codesentinel-frontend-10dn.onrender.com,http://localhost:3000

      - key: GITHUB_TOKEN
        sync: false

      - key: GROQ_API_KEY
        sync: false

  - type: web
    name: codesentinel-frontend
    runtime: node
    plan: free

    rootDir: codesentinel-ai/frontend

    buildCommand: npm install && npm run build

    startCommand: node .next/standalone/server.js

    autoDeploy: true

    healthCheckPath: /

    envVars:
      - key: NEXT_PUBLIC_API_BASE_URL
        value: https://codesentinel-backend-kdq6.onrender.com/api/v1